### PR TITLE
ES6 style

### PR DESCRIPTION
**Pull request by thomaswilburn**
LET'S BREAK EVERYTHING.

### CODE REVIEW

**Comment by ryanpitts** [comment]
Already had the lookup swapped in, such a good switch! I like the way you're adding `valueOf` too, that simplifies things.

**Comment by thomaswilburn** [comment]
Yeah, the lookup still makes me nervous because JS dates suck, and it may be better to use a standard formatted date string as the key instead, to make sure that precision isn't an issue.

**Comment by ryanpitts** [comment]
Yep, that seems safest. https://github.com/OpenNews/srccon-slackbot/commit/66ff73245f16043bf58e5db0cab8a10bba830db1

**Comment by ryanpitts** [comment]
ha, that's a nice optimization -- rather than creating a `timestamps` obj, running a match, and then posting the corresponding data from the `transcripts` obj, just move the timestamps as keys into the `transcripts` obj in the first place. Will try that.

**Comment by thomaswilburn** [comment]
That's also a place where using the arrow functions can really cleanup a lot of code without much boilerplate:

```js
//not this
var transcripts = {
  [moment.tz("2016-07-23", "America/Los Angeles").format("YYYY-MM-DD HH:mm")]: { ... }
}

//but this
var key = d => moment.tz(d, "America/Los Angeles").format("YYYY-MM-DD HH:mm");

var transcripts = {
  [key("2016-07-23")]: { ... }
}
```

**Comment by ryanpitts** [comment]
OK have folded in pretty much all the stuff in this PR, and learned some nice things (hello template strings!) along the way. Thanks!

Only thing that really didn't seem to work was removing the anonymous function from the `new CronJob` -- I don't at all know enough about `node-cron` to know why, but I can live with this.

**Comment by thomaswilburn** [comment]
In retrospect, the anonymous function is necessary for `new CronJob` because `checkTimeMatch` is undefined at the time of the call (it's not hoisted when defined using `var`). If you define it first, or move the instantiation to the very bottom to kick off program flow, and then you could pass in checkTimeMatch directly.

**Comment by ryanpitts** [comment]
ahhhh yes that makes perfect sense. And I do like firing things at the bottom, that seems better.

**Comment by ryanpitts** [comment]
ok here we go! https://github.com/OpenNews/srccon-slackbot/commit/b4e8be4dc0b42f04b249f1c8f80a33a16037d95e

**Comment by ryanpitts** [comment]
so in Python world, I'd most certainly add you to an AUTHORS or CONTRIBUTORS file. It looks to me like `author` in package.json only expects a string -- is that right? What's good practice in js world?

**Comment by thomaswilburn** [comment]
`contibutors` accepts an array of people, which can be strings or objects, if you're feeling verbose. https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by ryanpitts** [comment]
👍 done

**Pull request closed without merging**
